// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbbJhZrWNqKhvbdO-SXPG6XuKP5Dl818',
    appId: '1:962098212449:web:e27b1988feebb9f3da0420',
    messagingSenderId: '962098212449',
    projectId: 'sanad-f87d1',
    authDomain: 'sanad-f87d1.firebaseapp.com',
    storageBucket: 'sanad-f87d1.appspot.com',
    measurementId: 'G-VD7VVLJD14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqDbrnCRbQto3cD7x_EEuTfDiArthUYI',
    appId: '1:962098212449:android:dd52a7c40b9c77c1da0420',
    messagingSenderId: '962098212449',
    projectId: 'sanad-f87d1',
    storageBucket: 'sanad-f87d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3HibvfsDiqb8-ama06LQZ0VBITCbffjQ',
    appId: '1:701308330665:ios:91c4261da989c5c98c7fb8',
    messagingSenderId: '701308330665',
    projectId: 'my-social-app-1589e',
    storageBucket: 'my-social-app-1589e.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}